empath/absa/urls.py
from django.urls import path

from absa import views

app_name = 'absa'

urlpatterns = [
    path('', views.IndexView.as_view(), name='Index'),
    path('task/<int:task_id>/word-count/',
         views.WordCountView.as_view(), name='WordCount'),
    path('task/<int:task_id>/infer/', views.InferView.as_view(), name='Infer'),
    path('task/<int:task_id>/', views.TaskDetailView.as_view(), name='TaskDetail'),
]

empath/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='Login'),
    path('signup/', views.SignUpView.as_view(), name="SignUp"),
    path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
    path('check-user/', views.check_user, name='CheckUser')
]

empath/empath/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('', lambda req: redirect('/absa/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('absa/', include('absa.urls')),
    path('crawler/', include('crawler.urls'))
]

empath/templates/footer.html
<footer class="bg-light">
  <div class="container content">
    <div>
      ABSA-web-empath
      <a href="https://github.com/SeoJeongYeop/ABSA-web-empath" target="_blank">
        <i class="bi bi-github"></i>
      </a>
    </div>
  </div>
  <script>
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === name + '=') {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method);
    }
    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader('X-CSRFToken', csrftoken);
        }
      }
    });
  </script>
</footer>

empath/templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" name="viewport" content="width=device-width" />
  <title>EMPATH</title>

  <!-- Google Font -->
  <link
    href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200;400;500;700&display=swap"
    rel="stylesheet"
  />

  <!-- Jquery JS, Ajax -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

  <!-- Bootstrap5 -->
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
    crossorigin="anonymous"
  />

  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"
    defer
  ></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css" />

  <!-- Popperjs -->
  <script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha256-BRqBN7dYgABqtY9Hd4ynE+1slnEw+roEPFzQ7TRRfcg="
    crossorigin="anonymous"
    defer
  ></script>

  <!--D3.js-->
  <script src="https://d3js.org/d3.v7.min.js"></script>
  <!--D3.js Component-->
  <!--D3.js legend -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/2.25.6/d3-legend.min.js"></script>
  <!--D3.js format -->
  <script src="https://cdn.jsdelivr.net/npm/d3-format@3"></script>
  <script src="https://unpkg.com/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>

  <!-- JS LINK -->
  <script src="{% static 'js/base.js' %}" defer></script>

  <!-- CSS LINK -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/color.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/monitor.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/absa.css' %}" />
  <!-- favicon LINK -->
  <link rel="shortcut icon" href={% static 'images/favicon.ico' %} type="image/x-icon" /> <link rel="icon" href={%
  static 'images/favicon.ico' %} type="image/x-icon" />
</head>

empath/templates/header.html
<header class="navbar p-3">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-start w-100">
      <div class="d-flex col-12 col-md-3 justify-content-center justify-content-md-start">
        <a href="/absa" class="navbar-brand">
          <img width="42px" height="42px" src="/static/images/logo_base.png" alt="로고" style="border-radius: 50%" />
        </a>
        <a class="navbar-brand fs-3 bold text-nowrap align-middle" href="/">
          <span>EMPATH</span>
        </a>
      </div>

      <ul id="navbar" class="nav col-12 col-md-auto me-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/absa/" class="nav-link px-2">웹 담론 분석</a></li>
        {% if user.is_authenticated %}
        <li><a href="/crawler/" class="nav-link px-2">데이터 수집</a></li>
        {% endif %}
      </ul>

      <div class="text-end">
        {% if user.is_authenticated %}
        <form id="logout-form" method="post" action="{% url 'accounts:Logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary">로그아웃</button>
        </form>
        {%else%}
        <a href="/accounts/login/" class="btn btn-primary me-2" role="button">로그인</a>
        <a href="/accounts/signup/" class="btn btn-secondary" role="button">회원가입</a>
        {%endif%}
      </div>
    </div>
  </div>
</header>
{% block script %} {% endblock script %}

empath/templates/main.html
<!DOCTYPE html>
<html lang="ko">
  {% include 'head.html' %}
  <body>
    {% include 'header.html' %}

    <div id="body-wrapper" class="fouc">{% block content %} {% endblock %}</div>

    {% include 'footer.html' %}
  </body>
  {% block script %} {% endblock %}
</html>