empath/absa/urls.py
from django.urls import path

from absa import views

app_name = 'absa'

urlpatterns = [
    path('', views.IndexView.as_view(), name='Index'),
    path('task/<int:task_id>/word-count/',
         views.WordCountView.as_view(), name='WordCount'),
    path('task/<int:task_id>/infer/', views.InferView.as_view(), name='Infer'),
    path('task/<int:task_id>/', views.TaskDetailView.as_view(), name='TaskDetail'),
]

empath/accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='Login'),
    path('signup/', views.SignUpView.as_view(), name="SignUp"),
    path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
    path('check-user/', views.check_user, name='CheckUser')
]

empath/empath/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

urlpatterns = [
    path('', lambda req: redirect('/absa/')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('absa/', include('absa.urls')),
    path('crawler/', include('crawler.urls'))
]

empath/accounts/models.py
from django.db import models

# Create your models here.

empath/accounts/views.py
import logging

from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.db import DatabaseError, transaction
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView

from handle_error import get_fail_res


class LoginView(auth_views.LoginView):
    template_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class SignUpView(TemplateView):
    def get(self, request):
        template_name = 'signup.html'
        return render(request, template_name, context=None)

    def post(self, request):
        fail_reason = []

        username = request.POST.get('username')
        pw = request.POST.get('password')
        pw_check = request.POST.get('password-check')

        if len(username) < 5:
            fail_reason.append('Username은 5자 이상이여야 합니다.')
        if pw != pw_check:
            fail_reason.append('password가 일치하지 않습니다.')

        if len(fail_reason) > 0:
            return JsonResponse(get_fail_res("invalid_data_format", " ".join(fail_reason)))
        try:
            with transaction.atomic():
                user = User.objects.create_user(
                    username=username,
                    password=pw
                )
                user.save()
        except DatabaseError as e:
            logging.error(f'RegisterView DatabaseError: {e}')
            return JsonResponse(get_fail_res("db_exception"))

        except Exception as e:
            logging.error(f'RegisterView Exception: {e}')
            return JsonResponse(get_fail_res("undefined_exception"))
        return JsonResponse({'status': 'success'})


def check_user(request):
    # 회원가입 페이지에서 Username Check 버튼 누를 때 유효성 확인
    if request.method == 'POST':
        username = request.POST.get('username')
        if len(username) < 5:
            return JsonResponse(get_fail_res('invalid_data_format', 'Username은 5자 이상이여야 합니다.'))
        if check_duplicate_username(username):
            return JsonResponse(get_fail_res('invalid_data_format', '중복된 Username이 있습니다.'))

        return JsonResponse({'status': 'success'})


def check_duplicate_username(username):
    user = User.objects.filter(username=username)
    return len(user) > 0

empath/accounts/templates/login.html
{% extends 'main.html' %} {% load static %} {% block content %}
<div class="d-flex justify-content-center container my-5">
  <div class="col-lg-4 col-6">
    <div class="d-flex justify-content-center mb-3">
      <img src="/static/images/logo_large.png" alt="Logo" class="w-50 rounded-circle border" />
    </div>
    {% for error in form.non_field_errors %}
    <div class="text-center mb-3">
      {% if error == "Please enter a correct username and password. Note that both fields may be case-sensitive." %}
      <strong>Username과 비밀번호가 일치하지 않습니다</strong>
      {% else %}
      <strong>{{ error }}</strong>
      {% endif %}
    </div>
    {% endfor %}
    <form method="post" action="{% url 'accounts:Login' %}">
      {% csrf_token %}
      <div class="form-floating mb-3">
        <input type="text" class="form-control" name="username" id="username" placeholder="exampleusername" required />
        <label for="username">Username</label>
      </div>
      <div class="form-floating mb-3">
        <input
          type="password"
          class="form-control"
          name="password"
          id="password"
          placeholder="examplepw"
          autocomplete="off"
          required
        />
        <label for="password">Password</label>
      </div>
      <div class="d-flex flex-column">
        <button type="submit" class="btn btn-primary mb-2">Login</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block script %} {% endblock script %}

empath/accounts/templates/signup.html
{% extends 'main.html' %} {% load static %} {% block content %}
<div class="d-flex justify-content-center container my-5">
  <div class="col-lg-4 col-6">
    <div class="d-flex justify-content-center mb-3">
      <img src="/static/images/logo_large.png" alt="Logo" class="w-50 rounded-circle border" />
    </div>
    <form id="signin-form" method="post" action="." class="row">
      {% csrf_token %}
      <div class="mb-3">
        <label for="username">Username <span class="required-star">*</span></label>
        <div class="text-weak form-label">로그인에 사용할 아이디입니다.</div>
        <div class="input-group">
          <input
            type="text"
            class="form-control"
            id="username"
            name="username"
            placeholder="Username"
            onchange="return_username_check()"
            required
          />
          <button class="btn btn-outline-secondary" type="button" id="duplicate-check">Check</button>
        </div>
      </div>
      <div class="col-lg-6 mb-4">
        <label for="password">Password <span class="required-star">*</span></label>
        <div class="text-weak form-label">비밀번호는 4자 이상이어야 합니다.</div>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Password"
          minlength="4"
          autocomplete="off"
          required
          onChange="checkPassword();"
        />
      </div>
      <div class="col-lg-6 mb-4">
        <label for="password-check">Password Check <span class="required-star">*</span></label>
        <div id="password-check-sign" class="text-weak form-label">비밀번호를 다시 입력해주세요.</div>
        <input
          type="password"
          class="form-control"
          id="password-check"
          name="password-check"
          placeholder="Password Check"
          minlength="4"
          autocomplete="off"
          required
          onChange="checkPassword();"
        />
      </div>
      <div class="d-flex flex-column">
        <button type="submit" class="btn btn-primary">가입하기</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %} {% block script %}
<script>
  let is_modal_open = 0;
  let is_required_checked = false;
  let required_checklist = {};
  let categorySelect;
  let github_id_is_checked = false;
  let username_id_is_checked = false;
  let student_id_is_checked = false;

  function return_username_check() {
      username_id_is_checked = false;
      $('#duplicate-check').removeClass();
      $('#duplicate-check').addClass('btn btn-outline-secondary');
  };

  $(function(){

      {#유저 이름의 유효성을 체크하는 함수 실행#}
      $("#duplicate-check").on("click", () => {
          ajaxCheckDup();
      })
      // sign form
      const signinForm = document.getElementById("signin-form");
      signinForm.addEventListener("submit", (event) => {
          event.preventDefault();

          if (!username_id_is_checked) {
              alert('Username을 체크해 주세요.');
              event.preventDefault();
              return;
          } else {
              const ajax_form_data = new FormData(signinForm);
              const tag_list = [];
              for(let tag of $("#category_tag_list").find(".ss-value-text")){
                  tag_list.push($(tag).html());
              }
              ajax_form_data.append('category_tag_list', tag_list);
              $.ajax({
                  type: "POST",
                  url: "{% url 'accounts:SignUp' %}",
                  data: ajax_form_data,
                  dataType: 'json',
                  processData: false,
                  contentType: false,

                  success: function(data) {
                      console.log(data);
                      if(data['status']=="success"){
                          alert('회원가입이 완료되었습니다! 로그인 페이지로 이동합니다.')
                          window.location.href = "{% url 'accounts:Login' %}";
                      }
                      else{
                          alert( data['message'].join(',\n') );
                      }
                  },
                  error: function(data){
                      alert('Error Occured');
                  }
              });
          }
      });
  });
  function checkPassword(){
      let pswd = $("#password").val();
      let checkpswd = $("#password-check").val();
      if (checkpswd.length > 0){
          if(pswd == checkpswd){
              $("#password-check-sign").text("비밀번호가 일치합니다.")
              $("#password-check-sign").attr("class", "text-primary text-weak form-label");
          }else{
              $("#password-check-sign").text("비밀번호가 일치하지 않습니다.")
              $("#password-check-sign").attr("class", "text-danger text-weak form-label");
          }
      }
      else{
          $("#password-check-sign").text("비밀번호를 다시 입력해주세요.")
          $("#password-check-sign").attr("class", "text-weak form-label");
      }
  }

  function ajaxCheckDup(){
      console.log("ajaxCheckDup")
      if ($('#username').val().trim() === ""){
        alert("유저이름을 입력해주세요");
        $('#duplicate-check').removeClass('btn-outline-secondary');
        $('#duplicate-check').addClass('btn-outline-danger');
        return;
      }
      ajax_form_data=new FormData();
      ajax_form_data.append('username',$('#username').val());
      ajax_form_data.append('csrfmiddlewaretoken', csrftoken);
      $('#duplicate-check').html(
        `<div class="spinner-border spinner-border-sm" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>`);
      $.ajax({
          type: "POST",
          url: "{% url 'accounts:CheckUser' %}",
          data: ajax_form_data,
          dataType: 'json',
          processData: false,
          contentType: false,

          success: function(data) {
              console.log(data);
              if(data['status']=="success"){
                  username_id_is_checked = true;
                  alert('사용가능한 유저이름입니다.');
                  $('#duplicate-check').removeClass('btn-outline-secondary');
                  $('#duplicate-check').addClass('btn-outline-success');
              }
              else{
                  alert( data['message'] );
                  $('#duplicate-check').removeClass('btn-outline-secondary');
                  $('#duplicate-check').addClass('btn-outline-danger');
              }
              $('#duplicate-check').html("Check")
          },
          error: function(data){
              alert('Error Occured');
          }
      });
  }
</script>
{% endblock script %}